### ISSUE TITLE
WIS2box use

### ISSUE THREAD

**Issue by JaneWardle** [EUMETNET/community-component-docs#12]

**Comment by JaneWardle** [comment]
From Enrico, WMO: The wis2box software is developed with resources mostly from the WMO Secretariat and the technical lead from Canada. It would be good to collaborate with EUMETNET and its members to develop wis2box. This is the kind of synergy that could benefit EUMETNET and the wider WMO community. For this, we may discuss a letter of agreement if you think that can be of interest.

Tech team to discuss and agree if and how WIS2Box should be included in FEMDI development work.
Jane to respond to Enrico.

**Comment by eetuniemi** [comment]
This also aligns with the "data supply simulator" task

**Comment by JaneWardle** [comment]
From Jeremy: Wis2box is a good basis for a Data Supply Local Component. I thought that we would already be contributing – but E-SOH decided to build their own implementation. I guess that we should demonstrate how wis2box can be used for FEMDI (maybe at the Directors’ workshop?) and encourage Members to use it and (optionally) participate in development? I’m not sure if we have any EUMETNET activities that would directly participate in development re. E-SOH decision).
